name: 'f1_analytics_warehouse'
version: '1.0.0'
config-version: 2

# This tells dbt to look at the profiles.yml file we just made in this same directory
profile: 'f1_transform_profile'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  f1_analytics_warehouse:
    staging:
      +materialized: table
      +schema: staging

vars:
  bucket_name: "f1-pipeline-processed-layer-034381339055"